#!/bin/bash

pushd $OPENSHIFT_REPO_DIR
php boot_verify.php
if [ $? = 0 ]
then
    echo "MongoDB collection is empty. Running import..."
    mongoimport --db $OPENSHIFT_APP_NAME --collection tcl_metro_a --host $OPENSHIFT_MONGODB_DB_HOST --username $OPENSHIFT_MONGODB_DB_USERNAME --password $OPENSHIFT_MONGODB_DB_PASSWORD --port $OPENSHIFT_MONGODB_DB_PORT --type json --file $OPENSHIFT_REPO_DIR/tcl_metro_line_a.json

    # add a spatial index to our collection:
    php bootstrap.php
fi
popd
